# Composite action to setup python and install dependencies
# Useful for use in various pipelines as we usually have to setup python/dependencies

name: "Setup Dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install backend requirements
      shell: bash
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r ./local/requirements.txt
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Yarn
      shell: bash
      run: npm install --global yarn
    - name: Install frontend requirements
      shell: bash
      run: |
        cd frontend
        yarn install
