version: "3.9"

services:
  spark-master:
    image: apache/spark:3.5.7-java17-python3@sha256:7897b9a69efa94caccc52579e310a2fe68fb75b88a3d55b97b31568e5e233176
    container_name: spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "7077:7077"   # master rpc
      - "8080:8080"   # master ui
    networks:
      - flypipe-ntw

  spark-connect:
    image: apache/spark:3.5.7-java17-python3@sha256:7897b9a69efa94caccc52579e310a2fe68fb75b88a3d55b97b31568e5e233176
    container_name: spark-connect
    depends_on: [ spark-master ]
    # expose the Spark Connect endpoint
    ports:
      - "15002:15002"
      # optional: expose driver ui used by the connect server (changes per run)
      - "4040-4050:4040-4050"
    command: >
      /opt/spark/bin/spark-connect-server
      --packages org.apache.spark:spark-connect_2.12:3.5.7,io.delta:delta-spark_2.12:3.3.0
      --conf spark.master=spark://spark-master:7077
      --conf spark.ui.port=4040
      --conf spark.sql.execution.arrow.maxRecordsPerBatch=1000

  flypipe-mariadb:
    image: mariadb:10.11.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - flypipe-ntw

  flypipe-hive-metastore:
    build:
      context: .
      dockerfile: ./hive/Dockerfile
    ports:
      - 9083:9083
    depends_on:
      - flypipe-mariadb
    networks:
      - flypipe-ntw
    entrypoint: sh -c './../entrypoint.sh'

  flypipe-jupyter:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: flypipe-jupyter
    ports:
      - 8888:8888
    environment:
      FLYPIPE_DEFAULT_RUN_MODE: sequential
      GIT_PYTHON_REFRESH: quiet
    volumes:
      - ../.pylintrc:/.pylintrc
      - ../.coverage:/flypipe/.coverage
      - ../flypipe:/flypipe
      - ../scripts:/scripts
      - ./start.py:/etc/ipython/startup/start.py
      - ../docs/notebooks:/notebooks
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - spark-connect
    networks:
      - flypipe-ntw
    entrypoint: >
      jupyter-lab --notebook-dir /notebooks --allow-root
      --no-browser --port 8888 --ip 0.0.0.0
      --NotebookApp.token="" --NotebookApp.password=""

networks:
  flypipe-ntw:
