name: Build and Deploy Documentation via GitHub Pages

on:
  # TODO: we should only run this when deploying a version and not on pushes to certain branches
  push:
    branches: ["feat/documentation-graph"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch branches
        run: git fetch
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install requirements
        run: python -m pip install -r requirements_dev.txt
      - name: Build Sphinx Documentation
        run: sh docs/build_docs.sh
#        run: sphinx-multiversion docs/source docs/build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/build

  # Deploybuilt artifacts to github pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
