name: 'Calculate Version & Build Wheel'

on:
  push:
    branches: [ "main" ]

  # Allow for manual invocation
  workflow_dispatch:

  # Allow pipeline to be invoked from other pipelines
  workflow_call:

jobs:
#  verification:
#    uses: ./.github/workflows/verification.yml

  build-wheel:
#    needs: verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch branches
        run: git fetch
      - name: Setup Dependencies
        uses: './.github/actions/setup-dependencies'
      - name: Calculate new version number
        run: echo "VERSION_NUMBER=$(python scripts/calculate_version.py)" >> $GITHUB_ENV
      - name: Set version
        run: python scripts/set_version.py ${{ env.VERSION_NUMBER }}
      - name: Build Wheel
        run: flit build
      - name: Upload Wheel
        uses: actions/upload-artifact@v3
        with:
          name: flypipe-${{ env.VERSION_NUMBER }}-py3-none-any.whl
          path: ./dist
      # The below is a hack to allow us to access the version number in pipelines invoking this one
      - name: Save version to seperate file
        run: echo ${{ env.VERSION_NUMBER }} > version.txt
      - name: Upload Version
        uses: actions/upload-artifact@v3
        with:
          name: version.txt
