name: Build and Deploy Documentation via GitHub Pages

on:
  # TODO: we should only run this when deploying a version and not on pushes to certain branches
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow pipeline to be invoked from other pipelines
  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch branches
        run: git fetch
      - name: Setup Dependencies
        uses: './.github/actions/setup-dependencies'
      - name: Setup pandoc
        run: |
          # Script from https://nbanzyme.medium.com/install-pandoc-on-ubuntu-9cd9991735a2
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
          # Install
          sudo dpkg -i pandoc-2.19.2-1-amd64.deb
          # Check installation
          pandoc -v
      - name: Set production doc deployment flag
        run: PRODUCTION_DOCS_DEPLOY=1
      - name: Build Sphinx Documentation
        run: sh docs/build_docs.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/build

  # Deploybuilt artifacts to github pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
