name: 'Deployment (Production)'

on:

  # Allow for manual invocation
  workflow_dispatch:

jobs:
  cd-staging:
    uses: ./.github/workflows/cd-staging.yml

  test:
    needs: cd-staging
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo ${{ env.new_version }}
        