name: 'Deployment (Staging)'

on:
  push:
    branches: [ "main" ]

  # Allow for manual invocation
  workflow_dispatch:

jobs:
#  verification:
#    uses: ./.github/workflows/ci.yml

  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Wheel
        run: flit build
