name: Deployment (Staging)

on:
  push:
    branches: [ "main" ]

  # Allow for manual invocation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Verification
      uses: './ci.yml'
    - name: Build Wheel
      run: flit build
