name: Deployment (Staging)

on:
  push:
    branches: [ "main" ]

  # Allow for manual invocation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
      - name: Verification
        uses: './.github/actions/ci'
      - name: Build Wheel
        run: flit build
