name: 'Deploy'

on:

  # Allow for manual invocation
  workflow_dispatch:

jobs:
  build-wheel:
    uses: ./.github/workflows/build-wheel.yml

  deploy-pypi:
    needs: build-wheel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download version file
        uses: actions/download-artifact@v3
        with:
          name: version.txt
      - name: Store version number
        run: echo "VERSION_NUMBER=$(cat version.txt)" >> $GITHUB_ENV
      - name: Download wheel file
        uses: actions/download-artifact@v3
        with:
          name: flypipe-${{ env.VERSION_NUMBER }}-py3-none-any.whl
      - name: Create new branch
        run: |
          git checkout -b "release/${{ env.VERSION_NUMBER }}"
          git push origin "release/${{ env.VERSION_NUMBER }}"

  build-docs:
    needs: deploy-pypi
    uses: ./.github/workflows/build-docs.yml
