name: 'Deploy'

on:

  # Allow for manual invocation
  workflow_dispatch:

env:
  FLIT_USERNAME: manager.flypipe
  FLIT_INDEX_URL: https://test.pypi.org/legacy/

jobs:
#  predeploy:
#    uses: ./.github/workflows/predeploy.yml

  deploy-pypi:
    needs: predeploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Download version file
#        uses: actions/download-artifact@v3
#        with:
#          name: version.txt
#      - name: Store version number
#        run: echo "VERSION_NUMBER=$(cat version.txt)" >> $GITHUB_ENV
      - name: Store version number
        run: echo "VERSION_NUMBER=0.0.11 >> $GITHUB_ENV
      - name: Create new branch
        run: |
          git config --global user.email "flypipe@dummy.com"
          git config --global user.name "flypipe"
          git checkout -b "release/${{ env.VERSION_NUMBER }}"
          git add version.txt
          git commit -m 'chore: update version file'
          git push origin "release/${{ env.VERSION_NUMBER }}"
      - name: Upload to pypi
        run: |
          flit publish
        with:
          FLIT_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Upload Wheel
          uses: actions/upload-artifact@v3
          with:
            name: flypipe-${{ env.VERSION_NUMBER }}-py3-none-any.whl
            path: ./dist/flypipe-${{ env.VERSION_NUMBER }}-py3-none-any.whl

  build-docs:
    needs: deploy-pypi
    uses: ./.github/workflows/build-docs.yml
