# Release a new version of Flypipe docs. Changes that take place:
#
# - Documentation is regenerated and a new version added to the docs.

name: 'deploy-docs'

on:
  # Allow for manual invocation
  workflow_dispatch:

jobs:
  prepare-deployment:
    uses: ./.github/workflows/prepare-deployment.yml

  deploy-docs:
    needs: prepare-deployment
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: './.github/actions/setup-dependencies'

      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version.txt
          path: flypipe

      - name: Store version number
        run: echo "VERSION_NUMBER=$(cat flypipe/version.txt)" >> $GITHUB_ENV

      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog.md

      - name: Create and Push new release branch
        run: |
          git config --global user.email "flypipe@dummy.com"
          git config --global user.name "flypipe"
          git checkout -b "release/${{ env.VERSION_NUMBER }}"
          git add flypipe/version.txt
          git add changelog.md
          git commit -m 'chore: update version file, changelog'
          git push origin "release/${{ env.VERSION_NUMBER }}"

      - name: Deploy docs
        run: |
          git config --global user.email "flypipe@dummy.com"
          git config --global user.name "flypipe"
          git fetch
          make docs-deploy version=${{ env.VERSION_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
